'use client'

import { useEffect, useMemo, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Loader2, Sparkles } from 'lucide-react'
import { AUTONOMOUS_UI_ENABLED } from '@/lib/autonomous-ui'
import { MOCK_AI_ADVICE_TEXT } from '@/constants/mockData'

type Props = {
  brainState: 'unknown' | 'pending' | 'active' | 'error'
  refreshKey?: number
}

const FALLBACK = 'Unity Intelligence is currently optimizing your data...'
const LOCKED = 'Upgrade to Pro to view Unity Intelligence.'
const LOADING = 'Syncing with Brain...'
const RECONNECTING = 'Re-connecting to Unity Intelligence...'
const CACHED = 'Cached Data'
const AUTONOMOUS = 'Autonomous Mode'

export default function AiAdviceBox({ brainState, refreshKey = 0 }: Props) {
  const [loading, setLoading] = useState(false)
  const [text, setText] = useState<string>(MOCK_AI_ADVICE_TEXT)
  const [isCached, setIsCached] = useState(false)

  // IMPORTANT: "Brain approval" must not be a mandatory gate for initial page load.
  // The UI always shows mock content first, and optionally hydrates with Brain output when available.
  const autonomous = AUTONOMOUS_UI_ENABLED
  const canQueryBrain = !autonomous && brainState === 'active'
  const label = useMemo(() => {
    if (brainState === 'active') return 'Unity Intelligence'
    return 'Unity Intelligence'
  }, [brainState])

  async function load() {
    if (loading) return
    if (!canQueryBrain) {
      setText(MOCK_AI_ADVICE_TEXT)
      setIsCached(false)
      return
    }
    setLoading(true)
    try {
      // Unity Intelligence -> Brain /v1/analyze (server-side proxy).
      const res = await fetch('/api/brain/analyze', { cache: 'no-store' })
      const json = await res.json().catch(() => ({}))
      if (res.status === 403) {
        setText(MOCK_AI_ADVICE_TEXT)
        setIsCached(false)
        return
      }
      if (res.status === 402 || (json as any)?.locked) {
        setText(LOCKED)
        setIsCached(false)
        return
      }
      if ((json as any)?.error_code === 'unreachable') {
        setText(RECONNECTING)
        setIsCached(false)
        return
      }
      if (!res.ok) {
        // Try cached insight
        const cached = typeof window !== 'undefined' ? window.localStorage.getItem('uc_cached_unity_intelligence_v1') : null
        const cachedText = cached ? String(cached) : ''
        if (cachedText) {
          setText(cachedText)
          setIsCached(true)
        } else {
          setText(MOCK_AI_ADVICE_TEXT)
          setIsCached(false)
        }
        return
      }
      const insight = String((json as any)?.final || (json as any)?.insight || (json as any)?.text || '').trim()
      setText(insight || MOCK_AI_ADVICE_TEXT)
      setIsCached(false)
      try {
        if (typeof window !== 'undefined' && insight) window.localStorage.setItem('uc_cached_unity_intelligence_v1', insight)
      } catch {
        // ignore
      }
    } catch {
      const cached = typeof window !== 'undefined' ? window.localStorage.getItem('uc_cached_unity_intelligence_v1') : null
      const cachedText = cached ? String(cached) : ''
      if (cachedText) {
        setText(cachedText)
        setIsCached(true)
      } else {
        setText(MOCK_AI_ADVICE_TEXT)
        setIsCached(false)
      }
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    // When brain becomes active (or refreshKey bumps), pull fresh advice.
    load().catch(() => null)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [brainState, refreshKey])

  return (
    <Card className="border-0 shadow-xl overflow-hidden bg-gradient-to-br from-white to-[#f8fafc]">
      <div className="h-1.5 w-full bg-gradient-to-r from-purple-500 to-sky-500" />
      <CardHeader className="pb-3 rtl-text text-right">
        <div className="flex items-center justify-between gap-3">
          <CardTitle className="rtl-text text-right text-xl text-primary">{label}</CardTitle>
          <Button type="button" variant="outline" className="h-9" onClick={load} disabled={loading}>
            {loading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Sparkles className="h-4 w-4 mr-2" />}
            Refresh
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-2 rtl-text text-right">
        <div className="rounded-xl border border-slate-200 bg-white p-4 text-base text-slate-800 whitespace-pre-wrap">
          {loading ? LOADING : text || FALLBACK}
        </div>
        <div className="text-sm text-slate-500 rtl-text text-right">
          {autonomous || !canQueryBrain
            ? AUTONOMOUS
            : isCached
            ? CACHED
            : 'Generated by Unity Brain (multi-node consensus).'}
        </div>
      </CardContent>
    </Card>
  )
}


