import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase'

export const runtime = 'nodejs'

export async function GET(_req: NextRequest) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user?.id) {
    return NextResponse.json({ ok: false, error: 'Unauthorized', insights: [] }, { status: 401, headers: { 'Cache-Control': 'no-store' } })
  }

  // Local DB first: latest saved savings snapshot (generated by `/api/savings-finder`).
  try {
    const { data, error } = await supabase
      .from('user_savings_snapshots')
      .select('payload,created_at')
      .eq('user_id', user.id)
      .eq('kind', 'savings_finder')
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle()

    if (error) {
      return NextResponse.json(
        { ok: false, error: 'Local savings table is not ready.', details: error.message, insights: [] },
        { status: 500, headers: { 'Cache-Control': 'no-store' } }
      )
    }

    const payload: any = (data as any)?.payload || null
    const recs = Array.isArray(payload?.recommendations) ? payload.recommendations : []
    const insights = recs
      .slice(0, 25)
      .map((r: any) => ({
        title: String(r?.title_yi || r?.title || 'Saving'),
        merchant: r?.merchant ? String(r.merchant) : null,
        category: r?.category ? String(r.category) : null,
        monthly_savings: typeof r?.monthly_savings === 'number' ? r.monthly_savings : Number(r?.monthly_savings || 0) || null,
      }))
      .filter((x: any) => x.title)

    return NextResponse.json(
      { ok: true, source: 'supabase', created_at: (data as any)?.created_at || null, insights },
      { status: 200, headers: { 'Cache-Control': 'no-store' } }
    )
  } catch (e: any) {
    return NextResponse.json(
      { ok: false, error: 'Failed reading local insights.', details: e?.message || 'unknown', insights: [] },
      { status: 500, headers: { 'Cache-Control': 'no-store' } }
    )
  }
}


